from types import SimpleNamespace

from app.agents.initializer import InitializerAgent
from app.agents.node_agent import NodeAgent
from app.domain.enums import ProposalType, RiskLevel, TaskMode


class StubLLMClient:
    def __init__(self, payload):
        self.payload = payload
        self.calls: list[dict] = []

    def generate_json(self, **kwargs):
        self.calls.append(kwargs)
        return self.payload


def test_initializer_agent_uses_llm_payload(monkeypatch) -> None:
    monkeypatch.setattr(
        "app.agents.initializer.get_settings",
        lambda: SimpleNamespace(llm_taskspec_model="openai/gpt-4o-mini"),
    )
    client = StubLLMClient(
        {
            "goal": "Inspect nginx",
            "constraints": ["Use SSH only", "Require approval"],
            "success_criteria": ["Collect version info"],
            "risk_notes": ["Do not restart services"],
            "allowed_action_types": ["shell_command"],
            "disallowed_action_types": ["interactive_shell"],
            "initial_todo_template": ["Check nginx version", "Review config"],
            "operator_notes": "Generated by LiteLLM",
        }
    )

    draft = InitializerAgent(llm_client=client).generate(
        user_input="Inspect nginx safely",
        mode=TaskMode.AGENT_COMMAND,
    )

    assert draft.goal == "Inspect nginx"
    assert draft.allowed_action_types == ["shell_command"]
    assert draft.operator_notes == "Generated by LiteLLM"
    assert client.calls[0]["model"] == "openai/gpt-4o-mini"


def test_initializer_agent_falls_back_to_stub_on_invalid_payload(monkeypatch) -> None:
    monkeypatch.setattr(
        "app.agents.initializer.get_settings",
        lambda: SimpleNamespace(llm_taskspec_model="openai/gpt-4o-mini"),
    )
    client = StubLLMClient({"goal": "missing required fields"})

    draft = InitializerAgent(llm_client=client).generate(
        user_input="Inspect nginx safely",
        mode=TaskMode.AGENT_COMMAND,
    )

    assert draft.goal == "Inspect nginx safely"
    assert "Initializer stub" in draft.operator_notes


def test_node_agent_uses_llm_payload(monkeypatch) -> None:
    monkeypatch.setattr(
        "app.agents.node_agent.get_settings",
        lambda: SimpleNamespace(llm_proposal_model="openai/gpt-4o-mini"),
    )
    client = StubLLMClient(
        {
            "updated_todo": ["Review disk usage"],
            "proposal_type": "shell_command",
            "summary": "Inspect host facts",
            "content": {
                "summary": "Inspect host facts",
                "commands": ["uname -a", "whoami"],
                "success_check": "Commands exit 0",
            },
            "editable_content": {
                "summary": "Inspect host facts",
                "commands": ["uname -a", "whoami"],
                "success_check": "Commands exit 0",
            },
            "rationale": "Start read-only.",
            "risk_level": "low",
            "success_hypothesis": "We will learn enough to plan the next step.",
            "needs_user_input": False,
        }
    )

    draft = NodeAgent(llm_client=client).generate_proposal(
        mode=TaskMode.AGENT_COMMAND,
        node_name="node-1",
        round_index=1,
        todo_items=["Inspect host", "Review disk usage"],
    )

    assert draft.proposal_type == ProposalType.SHELL_COMMAND
    assert draft.risk_level == RiskLevel.LOW
    assert draft.content["commands"] == ["uname -a", "whoami"]
    assert client.calls[0]["model"] == "openai/gpt-4o-mini"


def test_node_agent_falls_back_to_stub_when_llm_payload_has_wrong_type(monkeypatch) -> None:
    monkeypatch.setattr(
        "app.agents.node_agent.get_settings",
        lambda: SimpleNamespace(llm_proposal_model="openai/gpt-4o-mini"),
    )
    client = StubLLMClient(
        {
            "updated_todo": [],
            "proposal_type": "remote_agent_task",
            "summary": "Wrong mode",
            "content": {"summary": "Wrong mode"},
            "editable_content": {"summary": "Wrong mode"},
            "rationale": "Wrong mode",
            "risk_level": "low",
            "success_hypothesis": "Wrong mode",
            "needs_user_input": False,
        }
    )

    draft = NodeAgent(llm_client=client).generate_proposal(
        mode=TaskMode.AGENT_COMMAND,
        node_name="node-1",
        round_index=1,
        todo_items=["Inspect host", "Review disk usage"],
    )

    assert draft.proposal_type == ProposalType.SHELL_COMMAND
    assert "FleetWarden round 1 on node-1" in draft.content["commands"][0]
