from dataclasses import dataclass

from pydantic import BaseModel, ValidationError

from app.config import get_settings
from app.domain.enums import TaskMode
from app.llm.client import LiteLLMJSONClient


@dataclass
class TaskSpecDraft:
    goal: str
    constraints: list[str]
    success_criteria: list[str]
    risk_notes: list[str]
    allowed_action_types: list[str]
    disallowed_action_types: list[str]
    initial_todo_template: list[str]
    operator_notes: str


class TaskSpecDraftPayload(BaseModel):
    goal: str
    constraints: list[str]
    success_criteria: list[str]
    risk_notes: list[str]
    allowed_action_types: list[str]
    disallowed_action_types: list[str]
    initial_todo_template: list[str]
    operator_notes: str


class InitializerAgent:
    def __init__(self, llm_client: LiteLLMJSONClient | None = None) -> None:
        self.llm_client = llm_client or LiteLLMJSONClient()

    def generate(self, *, user_input: str, mode: TaskMode) -> TaskSpecDraft:
        llm_draft = self._generate_with_llm(user_input=user_input, mode=mode)
        if llm_draft is not None:
            return llm_draft
        return self._generate_stub(user_input=user_input, mode=mode)

    def _generate_with_llm(self, *, user_input: str, mode: TaskMode) -> TaskSpecDraft | None:
        payload = self.llm_client.generate_json(
            model=get_settings().llm_taskspec_model,
            system_prompt=(
                "You generate a FleetWarden TaskSpec draft. "
                "Return only a JSON object with keys: "
                "goal, constraints, success_criteria, risk_notes, allowed_action_types, "
                "disallowed_action_types, initial_todo_template, operator_notes."
            ),
            user_prompt=(
                f"Task mode: {mode.value}\n"
                f"Operator request: {user_input.strip()}\n"
                "Create a concise, approval-friendly task spec for supervised SSH operations."
            ),
        )
        if payload is None:
            return None
        try:
            parsed = TaskSpecDraftPayload.model_validate(payload)
        except ValidationError:
            return None
        return TaskSpecDraft(**parsed.model_dump())

    def _generate_stub(self, *, user_input: str, mode: TaskMode) -> TaskSpecDraft:
        allowed = ["shell_command"] if mode == TaskMode.AGENT_COMMAND else ["remote_agent_task"]
        disallowed = ["interactive_shell", "background_daemon_installation"]
        mode_hint = (
            "Generate one non-interactive shell step per round."
            if mode == TaskMode.AGENT_COMMAND
            else "Generate delegation payloads for a remote coding agent."
        )
        return TaskSpecDraft(
            goal=user_input.strip(),
            constraints=[
                "Operate only through SSH.",
                "Require user approval before execution.",
                mode_hint,
            ],
            success_criteria=[
                "Each node reaches a terminal status with traceable evidence.",
                "Execution output is stored for review.",
            ],
            risk_notes=[
                "Avoid destructive commands without explicit operator review.",
                "Prefer read-only inspection before mutation.",
            ],
            allowed_action_types=allowed,
            disallowed_action_types=disallowed,
            initial_todo_template=[
                "Inspect current node state relevant to the goal.",
                "Propose the safest next action.",
                "Evaluate results against success criteria.",
            ],
            operator_notes="Generated by FleetWarden Initializer stub. Replace with LLM-backed agent later.",
        )
