from dataclasses import dataclass

from app.domain.enums import TaskMode


@dataclass
class TaskSpecDraft:
    goal: str
    constraints: list[str]
    success_criteria: list[str]
    risk_notes: list[str]
    allowed_action_types: list[str]
    disallowed_action_types: list[str]
    initial_todo_template: list[str]
    operator_notes: str


class InitializerAgent:
    def generate(self, *, user_input: str, mode: TaskMode) -> TaskSpecDraft:
        allowed = ["shell_command"] if mode == TaskMode.AGENT_COMMAND else ["remote_agent_task"]
        disallowed = ["interactive_shell", "background_daemon_installation"]
        mode_hint = (
            "Generate one non-interactive shell step per round."
            if mode == TaskMode.AGENT_COMMAND
            else "Generate delegation payloads for a remote coding agent."
        )
        return TaskSpecDraft(
            goal=user_input.strip(),
            constraints=[
                "Operate only through SSH.",
                "Require user approval before execution.",
                mode_hint,
            ],
            success_criteria=[
                "Each node reaches a terminal status with traceable evidence.",
                "Execution output is stored for review.",
            ],
            risk_notes=[
                "Avoid destructive commands without explicit operator review.",
                "Prefer read-only inspection before mutation.",
            ],
            allowed_action_types=allowed,
            disallowed_action_types=disallowed,
            initial_todo_template=[
                "Inspect current node state relevant to the goal.",
                "Propose the safest next action.",
                "Evaluate results against success criteria.",
            ],
            operator_notes="Generated by FleetWarden Initializer stub. Replace with LLM-backed agent later.",
        )

